### ISSUE TITLE
[NumberGuesser] Parse

### ISSUE THREAD

**Issue by pavel-b-novikov** [amalykh/nsudotnet#1]
```C#
try
{
 enteredNumber = int.Parse(curGuess);
}
catch (FormatException e)
{
 Console.WriteLine("Try to enter number next time");
 continue;
}
```
Вот слушайте, никогда не делайте парсеринг числа с ловлей exception-а. Найдите способ сделать без оного, а заодно нагуглите что происходит при выбросе exception-а и насколько это трудоемкий процесс. И мне расскажите.

**Comment by amalykh** [comment]
Исправлено.
Ну, когда у нас кидается Exception, у нас создаётся новый объект, и в стеке вызовов ищется подходящий для этого исключения обработчик. Соответственно, это достаточно трудоёмко.
В данном случае для нам этого не требуется.

**Comment by pavel-b-novikov** [comment]
Век живи - век учись.
