### ISSUE TITLE
[PerlinNoise] Именование

### ISSUE THREAD

**Issue by pavel-b-novikov** [amalykh/nsudotnet#3]
E_ARG_CNT, normalize..
Посмотрите в лекциях гайд по именованию, или прочитайте MS class library development guidelines/naming guidelines. А то глаз режет.

**Comment by amalykh** [comment]
Исправлено

**Comment by pavel-b-novikov** [comment]
```C#
  get { return Math.Max(0.0, Math.Min(_r, 255.0)); }
  set { _r = Math.Max(0.0, Math.Min(255.0, value)); }
```

Ну чтооо это такооое.. ну детский сад. Зачем вы эти значения еще раз клампуете на выходе, если они уже хранятся клампованными?

**Comment by amalykh** [comment]
Ещё раз исправлено.

**Comment by pavel-b-novikov** [comment]
Вы меня в могилу сведете.
