### ISSUE TITLE
[PerlinNoise] Алгоритм

### ISSUE THREAD

**Issue by pavel-b-novikov** [amalykh/nsudotnet#4]
Что-то я не очень въехал как работает ваша интерполяция. Расскажите подробнее.

**Comment by amalykh** [comment]
Метод CubicInterpolate класса CubicInterpolator отвечает за кубическую интерполяцию. Ему подаётся массив p[] — значения 4 ближайших точек, по которым производится интерполяция, и значение x, от 0 до 1, которое отвечает за то, насколько далеко находится точка, которую мы интерполируем от 1-ой.
Строим систему, в которой подставляем значение 1-й и 2-й точек (между которыми находится та, значение в которой надо узнать), а 0-ю и 3-ю точку приближаем производной. Решая эту систему, получаем те коэффициенты, которые используются в коде.

Теперь, на основе кубической, мы можем сделать бикубическую интерполяцию. Если мы зафиксируем какой-то x, то для него мы можем без проблем сделать кубическую интерполяцию. Таким образом, для 4-х значений x, делаем кубическую интерполяцию по отдельности, получаем 4 значения. Теперь нам по ним нужно сделать интерполяцию по y, для этого снова можно просто сделать кубическую интерполяцию.

Конечно, можно было просто скопировать матрицу для интерполяции, но такой вариант показался более понятным.

**Comment by pavel-b-novikov** [comment]
Ладно. Я просто действительно привык к другой реализации, но так тоже можно. По крайней мере используется наследование, как атрибут-такии ОО-программирования.
